### ISSUE TITLE
Adding new record fails with TypeError: urlopen() got multiple values for keyword argument 'body'

### ISSUE THREAD

**Issue by thijskh** [baszoetekouw/janus-py#3]
When running test.py:

```
Adding record


Traceback (most recent call last):
  File "./test.py", line 24, in <module>
    foo.updateById(id,extended)
  File "/home/thijs/janus-py/sr/sr.py", line 124, in updateById
    result = self._http_req('connections/%u' % eid, method='PUT', payload=newentity)
  File "/home/thijs/janus-py/sr/sr.py", line 62, in _http_req
    req = self._http.request(method, uri, headers=headers, body=body, redirect=False)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 142, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'
```

**Comment by thijskh** [comment]
Don't see this anymore.
